name: PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, ready_for_review, reopened]

jobs:
  pr-categorizer:
    name: Categorize PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/opened-pr-labeler.yml
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true

  require-pr-label:
    name: Require PR Label
    runs-on: ubuntu-latest
    needs: pr-categorizer
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: minimum
          count: 1
          labels: 'status: ready to merge'
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: 'status: do not merge'
